######################################################################
# Automatically generated by qmake (3.0) Tue Mar 29 23:37:50 2016
######################################################################

TEMPLATE = app
TARGET = xoptfoil
INCLUDEPATH += src/cpp

# Input
HEADERS += src/cpp/navigatorlist.h src/cpp/mainwindow.h
SOURCES += src/cpp/navigatorlist.cpp src/cpp/mainwindow.cpp src/cpp/gui_main.cpp 

QT += widgets
